### ISSUE TITLE
tech paper page may need info on downtime researchcloud

### ISSUE THREAD

**Issue by RolfHut** [eWaterCycle/ewatercycle.github.io#28]
Hi, I got the email pasted below and wondered if this will effect the environment for the reviewers of the tech paper. I think not but wanted to be sure. Please close this issue if no actions is needed.

the email:

The SURF Research Cloud service has a scheduled maintenance on the 13 Oct. 2021 from 07:00 - 12:30 pm CET [1]. 

Impact 
During the maintenance:

* running workspaces will operate as usual
* creating new workspaces will not be available

What will happen?
The backend infrastructure will be updated, namely the replacement of cloud hosting servers.

Questions?
For questions and remarks please contact the Helpdesk [2].

Kind regards, 
  
Nuno Ferreira 
(on behalf of the SRC team)   

[1]. https://servicedesk.surfsara.nl/wiki/display/WIKI/Service+Notices
[2]. http://servicedesk.surfsara.nl

**Comment by sverhoeven** [comment]
As running machines are not effected, we do not have to act.
